In [1]:
import numpy as np # импортирование библиотеки numpy

# Создание массивов

In [3]:
arr = np.array([1, 2, 3, 4, 5]) # создание массива на основе обычного List
arr

array([1, 2, 3, 4, 5])

In [4]:
arr_zeros = np.zeros((3, 2)) # создание двухмерного массива, заполненного нулями
arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

In [7]:
arr_arange = np.arange(1, 7).reshape(3, 2)

In [8]:
arr_arange

array([[1, 2],
       [3, 4],
       [5, 6]])

# Проверка размерности, типов

In [9]:
arr_arange.shape

(3, 2)

In [10]:
arr_arange.ndim

2

In [11]:
arr_arange.size

6

In [12]:
arr_arange.dtype

dtype('int64')

# Индексирование и срезы

In [13]:
arr_ar = np.arange(1, 11)

In [14]:
arr_ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr_ar[5]

np.int64(6)

In [17]:
arr_ar[1:3]

array([2, 3])

In [18]:
arr_arange[1, :]

array([3, 4])

# Простые операции и статистики


In [19]:
a = np.arange(10) ** 3

In [20]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [24]:
b = np.arange(20, 30) ** 3

In [25]:
b

array([ 8000,  9261, 10648, 12167, 13824, 15625, 17576, 19683, 21952,
       24389])

In [26]:
a + b

array([ 8000,  9262, 10656, 12194, 13888, 15750, 17792, 20026, 22464,
       25118])

In [27]:
a - b

array([ -8000,  -9260, -10640, -12140, -13760, -15500, -17360, -19340,
       -21440, -23660])

In [28]:
a * b

array([       0,     9261,    85184,   328509,   884736,  1953125,
        3796416,  6751269, 11239424, 17779581])

In [29]:
a ** b

array([                   0,                    1,                    0,
        2112283160366164147,                    0,  -619556583385162851,
                          0,  3552834457192890439,                    0,
       -1940147362841493831])

In [30]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))

In [31]:
b = a.transpose()

In [32]:
b

array([[[  0, 100],
        [ 10, 110]],

       [[  1, 101],
        [ 12, 112]],

       [[  2, 102],
        [ 13, 113]]])