In [1]:
import numpy as np # импортирование библиотеки numpy

# Создание массивов

In [2]:
arr = np.array([1, 2, 3, 4, 5]) # создание массива на основе обычного List
arr

array([1, 2, 3, 4, 5])

In [3]:
arr_zeros = np.zeros((3, 2)) # создание двухмерного массива, заполненного нулями
arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

In [5]:
arr_arange = np.arange(1, 7).reshape(3, 2)

In [6]:
arr_arange

array([[1, 2],
       [3, 4],
       [5, 6]])

# Проверка размерности, типов

In [7]:
arr_arange.shape

(3, 2)

In [8]:
arr_arange.ndim

2

In [9]:
arr_arange.size

6

In [10]:
arr_arange.dtype

dtype('int64')

# Индексирование и срезы

In [11]:
arr_ar = np.arange(1, 11)

In [12]:
arr_ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr_ar[5]

np.int64(6)

In [14]:
arr_ar[1:3]

array([2, 3])

In [15]:
arr_arange[1, :]

array([3, 4])

# Простые операции и статистики


In [16]:
a = np.arange(10) ** 3

In [17]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [18]:
b = np.arange(20, 30) ** 3

In [19]:
b

array([ 8000,  9261, 10648, 12167, 13824, 15625, 17576, 19683, 21952,
       24389])

In [20]:
a + b

array([ 8000,  9262, 10656, 12194, 13888, 15750, 17792, 20026, 22464,
       25118])

In [21]:
a - b

array([ -8000,  -9260, -10640, -12140, -13760, -15500, -17360, -19340,
       -21440, -23660])

In [22]:
a * b

array([       0,     9261,    85184,   328509,   884736,  1953125,
        3796416,  6751269, 11239424, 17779581])

In [23]:
a ** b

array([                   0,                    1,                    0,
        2112283160366164147,                    0,  -619556583385162851,
                          0,  3552834457192890439,                    0,
       -1940147362841493831])

In [24]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))

In [25]:
b = a.transpose()

In [26]:
b

array([[[  0, 100],
        [ 10, 110]],

       [[  1, 101],
        [ 12, 112]],

       [[  2, 102],
        [ 13, 113]]])

In [27]:
stats = np.array([[1,2,3],[4,5,6]])

In [28]:
stats.sum() # нахождение суммы

np.int64(21)

In [29]:
stats.sum(axis=0) # сумма по столбцу

array([5, 7, 9])

In [31]:
stats.sum(axis=1) # сумма по строкам

array([ 6, 15])

In [32]:
stats.min(axis=0) # минимальное по колонкам

array([1, 2, 3])

In [33]:
stats.max(axis=1) # максимальное по строкам

array([3, 6])

In [34]:
stats.mean() # среднее в массиве

np.float64(3.5)

In [35]:
rand_arr = np.random.rand(3, 4)

In [36]:
rand_arr

array([[0.60114431, 0.7586985 , 0.36774289, 0.27077866],
       [0.0824529 , 0.72334037, 0.38734395, 0.89909322],
       [0.10201584, 0.61405619, 0.79123108, 0.62045636]])

In [37]:
rand_arr.mean()

np.float64(0.5181961895412853)

In [38]:
rand_arr.var() # вычисление дисперсии

np.float64(0.06751125025565628)

In [39]:
rand_arr.std() # вычисление стандартного отклонения

np.float64(0.2598292713603613)